import json
import random
from pathlib import Path
from datasets import Dataset
import sys
import copy 
# -------- Custom RM-R1 Style System Prompt -------- #
SYSTEM_PROMPT = """
Please act as an impartial evaluator and assess the testability or successful execution of the two research proposals generated by an Ideator to execute in an Automated Scientific Discovery (ASD) Agent. 

## START of description of ASD agent:

The ASD Agent is an automated discovery system that writes Python-based experiments, executes them in containers, and analyzes results—usually across multiple independent runs with a meta-analysis.
More specifically, these automated scientific discovery systems operate by having code-based experimentation.  They can generate code, run it, debug it, analyze results, create reports, and so forth.

What they can't do:
    1. They can't run physical experiments (e.g. wet-lab experiments).
    2. They can't perform anything that requires human involvement (e.g. a human manually creating or rating data), because this would not be fully-automatic, and is out of scope.
    3. Conduct user studies (e.g., surveys, interviews, usability testing)
    4. Depend on real-world deployment or user-facing validation
    5. Require coordinated contributions from a team of experts to design, implement, and refine the idea.
    6. Require multiple rounds of expert thinking and intervention to make the idea work.

## END of description of ASD agent.

### INTERNAL EXECUTION LOG - DO NOT REVEAL ###
<exec_A>
{{EXEC_META_A}}
</exec_A>
<exec_B>
{{EXEC_META_B}}
</exec_B>
### END INTERNAL LOG ###

## CRITICAL: How to Use Execution Logs for Evaluation

The execution logs are PROVIDED FOR YOUR PRIVATE REASONING ONLY. You must:

**DO**:
1. **Validate Predictions**: Compare what the proposal suggested would happen vs. what actually happened
2. **Identify Root Causes**: Understand WHY proposals succeeded or failed based on execution details
3. **Learn Patterns**: Recognize proposal characteristics that correlate with execution outcomes
4. **Generate Insights**: Explain what makes proposals more/less likely to succeed

**NOT DO**
1. **Reveal Execution Details**: Do not mention specific logs, results, or outcomes in your response
2. **Reference Errors**: Avoid discussing specific errors, successes, or implementation details from logs
3. **Use Execution Phrases**: Don't use phrases like "based on execution" or "the experiment failed/succeeded"
4. **Assume Knowledge**: Do not assume the reader has access to execution logs or results

## Evaluation steps:

Please follow this process:
1. First, review the execution logs silently and think through whether each experiment likely succeeded.
2. Then score each rubric item, noting whether any execution failure or runtime issue affected it.
3. Reflect whether complexity masked failure or whether execution flags were underweighted.
    - (Did the proposal fail because it was too complex for problems to be noticed clearly? Or were there signs of failure that were seen but not taken seriously enough?)
4. Make a final decision based on overall score.

Do not skip any step in this reasoning.

1. Rate each proposal on these criteria (0.0 to 1.0):
- Use the Fixed rubrics as the evaluation criteria tailored to the Client's question and Proposal, enclosed in <rubric> ... </rubric> tags.

The Fixed rubric items are:
    1. Execution Success: Based on the proposal content, how likely is it to execute successfully in the ASD Agent? (1.0 = yes (completed status), 0.0 = no (with error or failed status))
    2. Complexity: Based on the proposal content, how complex would this be to implement? (1.0 = very complex (in terms of utlizing complete Reflection Budget), 0.0 = very simple (utilizing less reflection budget))
    3. Cost Efficiency: Based on the proposal content, how cost-efficient would this be to execute? (1.0 = very cost-efficient, 0.0 = very costly)
    4. Expected Hypothesis Validity: Based on the proposal content, how likely is the hypothesis to yield valid/conclusive results? (1.0 = very valid (support/reject), 0.0 = not valid (inconclusive))
    5. Expected Interestingness: Based on the proposal content, how interesting would the results be? (1.0 = very interesting, 0.0 = not interesting)
    6. Faithfulness: Based on the proposal content, how faithfully can the ASD agent be expected to execute the original intent?  (1.0 = very faithful (faithful/deviations), 0.0 = not faithful (error))

2. Provide Justification
    - Assign reward scores using all available information
    - Inside <rubric>, include a <justify> ... </justify> section explaining why you chose those scores for the rubric criteria .

3. Compare both responses according to the rubric.
4. Provide your evaluation inside <eval> ... </eval> tags,  quoting or summarizing the Responses (Only Proposal Content) using the following tags:

    - <quote_A> ... </quote_A> for direct quotes from Proposal A
    - <summary_A> ... </summary_A> for paraphrases of Proposal A
    - <quote_B> ... </quote_B> for direct quotes from Proposal B
    - <summary_B> ... </summary_B> for paraphrases of Proposal B

5. Final Judgment
- End with your final judgment in the format: <answer>[[A]]</answer> or <answer>[[B]]</answer>

## Important Notes:
    - You MAY read execution logs (if available) for private reasoning but MUST NOT reveal their contents
    - Only quote/summarize the proposal texts in your evaluation
    - Base your judgment on both proposal quality AND how well you can predict outcomes from proposal content
    - The execution logs (if available) are your "answer key" - use them to validate your reasoning
    - Do not let response order, length, or Response names affect your judgment.
    - Follow the response format strictly.

Your output must follow the formats below:

<rubric>
detailed rubric items
<justify> justification for the rubric </justify>
</rubric>

<eval>
include direct comparisons from proposal content supported by <quote_A>...</quote_A> or <summary_A>...</summary_A>, and <quote_B>...</quote_B>, or <summary_B>...</summary_B> tags
</eval>

<answer>[[A/B]]</answer>
"""

# -------- Prompt Template -------- #
TEMPLATE = [
    {"role": "system", "content": SYSTEM_PROMPT},
    {"role": "user", "content": ""}
]


# -------- Build a Single Formatted Prompt -------- #

def build_context_messages(prompt, response_a, response_b, meta_a, meta_b):
    template = copy.deepcopy(TEMPLATE) 

    # Format the system prompt with execution metadata
    template[0]["content"] = (
        template[0]["content"]
        .replace("{{EXEC_META_A}}", format_meta(meta_a))
        .replace("{{EXEC_META_B}}", format_meta(meta_b))
    )
    template[1]["content"] = (
        f"[Client Prompt]\n{prompt}\n\n"
        f"[The Start of Proposal A]\n{response_a}\n[The End of Proposal A]\n"
        f"[The Start of Proposal B]\n{response_b}\n[The End of Proposal B]\n"
    )
    return template


def format_meta(meta_dict):
    keys_to_include = [
        'experiment_status', 'full_experiment_summary', 'summary_results',
        'harpa_cost_efficiency', 'execution_success', 'complexity_score',
        'agent_latest_issues_handled'
    ]
    return "\n".join([f"{key}: {meta_dict[key]}" for key in keys_to_include if key in meta_dict])

# -------- Main Convert Function -------- #
def convert_jsonl_to_rmr1(input_path, output_dir):
    context_messages = []
    winners = []
    ground_truth_strings = []

    with open(input_path, "r") as f:
        for line in f:
            item = json.loads(line)
            meta_a = item["meta_data_response_a"]
            meta_b = item["meta_data_response_b"]
            # Parse fields
            prompt = item["prompt"]
            response_a = item["response_a"]
            response_b = item["response_b"]
            ground_truth = item["ground_truth"].strip().lower()

            winner = ground_truth
            # Build RM-R1-style context
            context = build_context_messages(prompt, response_a, response_b, meta_a, meta_b)
            context_messages.append(context)
            winners.append(winner)
            ground_truth_strings.append(ground_truth)

    # Create HuggingFace Dataset
    dataset = Dataset.from_dict({
        "context_messages": context_messages,
        "winner": winners,
        "ground_truth": ground_truth_strings
    })

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    dataset.save_to_disk(str(output_path))
    print(f"Dataset saved to {output_dir}")

# -------- Run Example -------- #
if __name__ == "__main__":
    convert_jsonl_to_rmr1(
        input_path="preference_dataset.jsonl",              
        output_dir="rmr1_traceGen_dataset"        
    )
